apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-plugin
  labels:
    app: autoscaler-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler-plugin
  template:
    metadata:
      labels:
        app: autoscaler-plugin
    spec:
      containers:
      - name: autoscaler-plugin
        image: docker.io/library/autoscaler-plugin:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        startupProbe:
          httpGet:
            path: /health
            port: 8001
          failureThreshold: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: autoscaler-plugin-svc
spec:
  selector:
    app: autoscaler-plugin
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: NodePort