apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.targetDeployment.name }}-svc
  namespace: {{ .Values.targetDeployment.namespace }}
spec:
  selector:
    app: {{ .Values.targetDeployment.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}